baseurl: "/genius-invokation-database"
url: "https://oxygen-dioxide.github.io"

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

whitelist:
  - jekyll-relative-links
  - jekyll-redirect-from